name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: codeabode
            asset_name: linux-amd64
          - os: macos-latest
            artifact_name: codeabode
            asset_name: macos-arm64

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        python3 -m venv venv

        source venv/bin/activate

        pip install setuptools
        pip install --upgrade setuptools
        pip install -r newreqs.txt
        venv/bin/pyinstaller -F codeabode.py
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: new
